name: gcp_functions_framework_firestore
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  functions_framework: ^0.4.0
  dart_firebase_admin: ^0.2.0
  protobuf: ^3.1.0
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
  http: '>=0.13.0 <2.0.0'
  test: ^1.15.7
  test_process: ^2.0.0
