name: aws_lambda
description: AWS Lambda function in Dart
version: 1.0.0

environment:
  sdk: ^3.4.1

dependencies:
  aws_lambda_dart_runtime_ns: ^0.1.0
  aws_dynamodb_api: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
