# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mobilapp
service: aws-lambda-dart-example

provider:
  name: aws
  runtime: provided
  timeout: 30
  region: eu-central-1
  architecture: arm64
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/arm64

functions:
  hello-world:
    image:
      name: appImage
      command:
        - hello-world