org: mobilapp
service: aws-lambda-dart-example

provider:
  name: aws
  runtime: provided
  timeout: 30
  region: eu-central-1
  architecture: arm64
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/arm64
  environment:
    AWS_REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:DescribeStream
            - dynamodb:ListStreams
          Resource:
            - !GetAtt TodosTable.Arn
            - !Join ['/', [!GetAtt TodosTable.Arn, 'stream/*']]

functions:
  processTodo:
    image:
      name: appImage
    command: on-create-todo
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt TodosTable.StreamArn
          batchSize: 1
          startingPosition: LATEST
          maximumRetryAttempts: 2

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES